# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"coroutine": "coroutines.ipynb",
         "json_coro": "coroutines.ipynb",
         "MakeDf": "makeDf.ipynb",
         "SendableDf": "sendableDf.ipynb",
         "untar": "untarify.ipynb",
         "powerup_untar": "untarify.ipynb"}

modules = ["coroutines.py",
           "makeDf.py",
           "sendableDf.py",
           "untarify.py"]

doc_url = "https://sapal6.github.io/json2dataframe/"

git_url = "https://github.com/sapal6/json2dataframe/tree/master/"

def custom_doc_links(name): return None
