# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"untar": "00_untarify.ipynb",
         "powerup_untar": "00_untarify.ipynb",
         "coroutine": "01_coroutines.ipynb",
         "json_coro": "01_coroutines.ipynb",
         "SendableDf": "02_sendableDf.ipynb",
         "MakeDf": "03_makeDf.ipynb"}

modules = ["untarify.py",
           "coroutines.py",
           "sendableDf.py",
           "makeDf.py"]

doc_url = "https://sapal6.github.io/json2dataframe/"

git_url = "https://github.com/sapal6/json2dataframe/tree/master/"

def custom_doc_links(name): return None
