# AUTOGENERATED! DO NOT EDIT! File to edit: 01_coroutines.ipynb (unless otherwise specified).

__all__ = ['coroutine', 'json_coro']

# Cell
#export
import ijson

def coroutine(func):
    """Decorator to prime up a corotuine
     It calls the next() of a coroutine"""
    def start(*args, **kwrgs):
        coro = func(*args, **kwrgs)
        coro.__next__()
        return coro
    return start

@coroutine
def json_coro(key_str: str, target):
    "coroutine to parse json files from a directory"

    while True:
        files = (yield)
        data = []
        for file in files:
            print(f'Parsing {file}')
            with open(file, 'r') as f:
                objects = ijson.items(f, key_str)
                data+=list(objects)
        target.send(data)