# AUTOGENERATED! DO NOT EDIT! File to edit: 03_makeDf.ipynb (unless otherwise specified).

__all__ = ['MakeDf']

# Cell
#required for scripts in jupyter notebook
from pathlib import Path
from .coroutines import *
from .sendableDf import *

# Cell
#todo: test it
#todo: make the import of corutines correct and use the corituines.method name below
class MakeDf:
    """
    Provides API to create dataframe from json files.
    Provides the method `dataframe()` which can be used to
    create dataframes.
    """
    def __init__(self, key_str: str):
        self.key_str = key_str
        self.df_coro = SendableDf(self.key_str)
        self.target = json_coro(key_str, self.df_coro)

    def __producer(self, json_files: list):
        """Internal method. Acts as producer
         to send the data to the next corutine

         Accepts the list of json files and the
         name of the sink."""
        self.target.send(json_files)
        self.target.close()

    def dataframe(self, json_files_dir: str):
        """High level API to send data to producer.

           Accepts the path to the directory where
           json files are stored.

           Returns a dataframe"""
        json_files = [file for file in Path(json_files_dir).iterdir() if  file.suffix == '.jsonl']
        self.__producer(json_files)
        df = self.df_coro.collect_df()
        return df