# AUTOGENERATED! DO NOT EDIT! File to edit: sendableDf.ipynb (unless otherwise specified).

__all__ = ['SendableDf']

# Cell
import pandas as pd

# Cell
class SendableDf:
    """
    A class that mimics a coroutine receiving values.
    Coroutine are sent values via their send() method. This class defines such a
    method so that values sent into it are converted into the dataframe, which can be
    inspected later.

    Inspired by ##from isjon utils code--https://github.com/ICRAR/ijson/ blob/master/ijson/utils.py
    """
    def __init__(self, key_str: str):
        self.key_str = key_str
        self.rows = list

    def send(self, column_data:list):
        """
        send overrides a corutines `send()` method.
        Accepts a list of json data
        Returns a list
        """
        self.rows=column_data

    def collect_df(self):
        """
        creates a dataframe from the list of data collected by send
        """
        return pd.DataFrame(self.rows, columns=[self.key_str])